name = "malpanimsoulstrings"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
ENVIRONMENT = "production"
CANONICAL_DOMAIN = "www.malpanimsoulstrings.com"
PRIMARY_PHONE = "+917744009295"
